lowercase cd

diff --git a/githubhook/init.d/githubhook b/githubhook/init.d/githubhook
--- a/githubhook/init.d/githubhook
+++ b/githubhook/init.d/githubhook
@@ -14,7 +14,7 @@ do_start()
 {
         if [ ! -f "$LOCK_FILE" ] ; then
                 echo -n $"Starting $SERVER: "
-                runuser -l "$USER" -c "CD $ROOT_DIR; $DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
+                runuser -l "$USER" -c "cd $ROOT_DIR; $DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
                 RETVAL=$?
                 echo
                 [ $RETVAL -eq 0 ] && touch $LOCK_FILE
