tiny little changes

diff --git a/githubhook/init.d/quickshare b/githubhook/init.d/quickshare
--- a/githubhook/init.d/quickshare
+++ b/githubhook/init.d/quickshare
@@ -14,17 +14,17 @@ USER="web"
 DAEMON="/usr/local/bin/supervisor"
 ROOT_DIR="/home/web/ugot.com/QuickShare"
 
-SERVER="$ROOT_DIR/app.js"
+SERVER="-q -w $ROOT_DIR/app.js,$ROOT_DIR/server,$ROOT_DIR/client $ROOT_DIR/app.js"
 LOG_FILE="$ROOT_DIR/app.js.log"
 
 LOCK_FILE="/var/lock/subsys/node-server-quickshare"
 
 do_start()
 {
-        npm install
         if [ ! -f "$LOCK_FILE" ] ; then
                 echo -n $"Starting $SERVER: "
-                runuser -l "$USER" -c "cd $ROOT_DIR; $DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
+
+                runuser -l "$USER" -c "cd $ROOT_DIR; npm install; NODE_ENV=production $DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
                 RETVAL=$?
                 echo
                 [ $RETVAL -eq 0 ] && touch $LOCK_FILE
@@ -37,7 +37,7 @@ do_stop()
 {
         echo -n $"Stopping $SERVER: "
         pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
-        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
+        kill $pid > /dev/null 2>&1 && echo_success || echo_failure
         RETVAL=$?
         echo
         [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
